default: &default
  adapter: mysql2
  encoding: utf8
  host: localhost

development:
  <<: *default
  pool: 5
  timeout: 5000
  database: blog_development

production:
  <<: *default
  database: blog_production
  username: ENV['database_username']
  password: ENV['database_password']
